name: "Upload SARIF"

# Run workflow each time code is pushed to your repository and on a schedule.
# The scheduled workflow runs every Thursday at 15:45 UTC.
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write
      # only required for workflows in private repositories
      actions: read
      contents: read
    steps:
      # This step checks out a copy of your repository.
      - name: Checkout repository
        run: |
         mkdir gitlab
         cd gitlab
         git clone https://cve-token:glpat-gWzQgP9WvgyC9x4yJdKK@gitlab.com/epteck-pk/ept-teams/epte-ext/cve-check
#       - name: Upload SARIF file
#         uses: github/codeql-action/upload-sarif@v2
#         with:
#           sarif_file: /home/runner/work/Vaillant/Vaillant/gitlab/cve-check # Path to SARIF file relative to the root of the repository
#           category: my-analysis-tool
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ./cve-output
          category: my-analysis-tool
